### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by Hxiaowu666** [haibao-yu/FFNet-VIC3D#3]
When I run `python tools/train.py ffnet_work_dir/config_basemodel.py`

Traceback (most recent call last):
  File "/root/miniconda3/envs/dair/lib/python3.7/site-packages/mmcv/utils/registry.py", line 51, in build_from_cfg
    return obj_cls(**args)
  File "/root/FFNet-VIC3D-main/mmdet3d/datasets/v2x_dataset.py", line 83, in __init__
    self.__load_v2x_annotations()
  File "/root/FFNet-VIC3D-main/mmdet3d/datasets/v2x_dataset.py", line 116, in __load_v2x_annotations
    anno_path = os.path.join(self.data_root, info['cooperative_label_w2v_path'])
KeyError: 'cooperative_label_w2v_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/train.py", line 226, in <module>
    main()
  File "tools/train.py", line 189, in main
    datasets = [build_dataset(cfg.data.train)]
  File "/root/FFNet-VIC3D-main/mmdet3d/datasets/builder.py", line 32, in build_dataset
    build_dataset(cfg['dataset'], default_args), cfg['times'])
  File "/root/FFNet-VIC3D-main/mmdet3d/datasets/builder.py", line 41, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/root/miniconda3/envs/dair/lib/python3.7/site-packages/mmcv/utils/registry.py", line 54, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "V2XDataset: 'cooperative_label_w2v_path'"

**Comment by fanwu66** [comment]
你好，请问你这个问题解决了吗

**Comment by haibao-yu** [comment]
Thanks for you feedback. We have solved this problem. You can pull the newest repo.
